# Menu
menu:
  主页: /
  归档: /archives
  # 相册: /gallery
  # 关于: /about
rss: /atom.xml

# Miscellaneous
favicon: /favicon.ico
# brand: /images/hexo.svg
brand: /images/portrait.png

# 目录
toc:
  maxDepth: 3
# Ocean 主页视频
# 多种格式的视频用于支持不同的浏览器，这里只需要配置好路径，前提是我把视频相关文件统一目录存放。
ocean:
  overlay: true      # 可选，false 则 Ocean 视频下方的笔触式遮盖不显示
  path: /images/ocean/      # 视频统一存放路径，格式 mp4/ogg/webm
  brand: /images/portrait.png      # 可选，一个小 Logo

# 内容
excerpt_link: 阅读全文...
share_text: 分享
nav_text:
  page_prev: 上一页
  page_next: 下一页
  post_prev: 前一篇
  post_next: 后一篇

# fancybox
fancybox: true

# Local search
search_text: 搜索

# 版权申明
declare_type: 2
licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
# licensee_name: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'
licensee_name: 'CC BY-NC-SA 4.0'
licensee_img: https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png

# 打赏
reward_type: 2 # 每篇文章都打赏
alipay_QRcode_url: https://raw.githubusercontent.com/JackZhouMine/jack-picture/master/alipay2.jpg # 支付宝收款码
wechat_QRcode_url: https://raw.githubusercontent.com/JackZhouMine/jack-picture/master/weixin2.jpg # 微信打赏码

# 推荐阅读 需要 hexo-recommended-posts 支持
recommended_posts:
  enable: true

# Gitalk
gitalk:
  enable: true      # 默认关闭评论 开启：true
  clientID: 90f92ec37c1bf3ff8c87 # 申请 GitHub Application 网页上对应的 Client ID 与 Client Secret 参数
  clientSecret: c746c91801c749223e933fb3393dd4fd7f0e53a6 # 同上
  repo: blog-comment # 创建的仓库名称
  owner: jackzhoumine # Github ID https://api.github.com/users/jackzhoumine 获取
  admin: jackzhoumine # Github ID 21340150