# Menu
menu:
  主页: /
  归档: /archives
  # 相册: /gallery
  # 关于: /about
rss: /atom.xml

# Miscellaneous
favicon: /favicon.ico
# brand: /images/hexo.svg
brand: /images/portrait.png

# Ocean 主页视频
# 多种格式的视频用于支持不同的浏览器，这里只需要配置好路径，前提是我把视频相关文件统一目录存放。
ocean:
  overlay: true      # 可选，false 则 Ocean 视频下方的笔触式遮盖不显示
  path: /images/ocean/      # 视频统一存放路径，格式 mp4/ogg/webm
  brand: /images/portrait.png      # 可选，一个小 Logo

# 内容
excerpt_link: 阅读全文...
share_text: 分享
nav_text:
  page_prev: 上一页
  page_next: 下一页
  post_prev: 前一篇
  post_next: 后一篇

# fancybox
fancybox: true

# Local search
search_text: 搜索

# Gitalk
gitalk:
  enable: false      # 默认关闭评论 开启：true
  clientID:      # 申请 GitHub Application 网页上对应的 Client ID 与 Client Secret 参数
  clientSecret:      # 同上
  repo:      # 创建的仓库名称
  owner:      # Github ID
  admin:      # Github ID